spring.application.name=teamflow-api
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/teamflow}
spring.datasource.username=${DATABASE_USERNAME:teamflow}
spring.datasource.password=${DATABASE_PASSWORD:teamflow}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

app.jwt.secret=${JWT_SECRET}